// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{
        "name": "MadeWithMv",
        "status": true,
        "description": "",
        "parameters": {
          "Show Made With MV": "true",
          "Made with MV Image": "splash screen",
          "Show Custom Splash": "false",
          "Custom Image": "",
          "Fade Out Time": "120",
          "Fade In Time": "120",
          "Wait Time": "360"
        }
},
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"20","screenWidth":"960","screenHeight":"600","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"on"}},
{"name":"SimpleMenuLayout","status":true,"description":"シンプルなメニュー画面を実装します。","parameters":{"----基本的な設定----":"","メニュー幅":"240","メニュー列数":"1","メニューX座標":"{\"basis\":\"center\",\"correction\":\"0\"}","メニューY座標":"{\"basis\":\"center\",\"correction\":\"0\"}"}},
{"name":"StatusBustImage","status":true,"description":"バストアップ表示プラグイン","parameters":{"画像X座標":"100","画像Y座標":"100","装備_画像X座標":"","装備_画像Y座標":"","スキル_画像X座標":"","スキル_画像Y座標":"","メイン_画像X座標":"480","メイン_画像Y座標":"600","表示優先度":"0","ベース画像原点":"2","追加画像原点":"2"}},
{"name":"ponidog_BackLog_utf8","status":true,"description":"バックログ及びメッセージ周りの補填関係","parameters":{"nBackLogDisplayLine":"12","nBackLogLimitMax":"-1","nBackLogButtonUp":"0","nBackLogButtonDown":"0","nBackLogButtonHide":"0","bBackLogNameOn_forYepMessageCore":"true","bBackLogNameOn_Flame":"●","bBackLogNameOn_Flame2":"","sBackLogNoFaceSymbol":"★","sBackLogNoFaceSpace":""}},
{"name":"UTA_MessageSkip","status":true,"description":"特定キーを押す事でメッセージをスキップできるようにします。","parameters":{"Skip Key":"control","Show Trace":"false"}},
{"name":"GamepadConfig","status":true,"description":"ゲームパッド向けにボタンコンフィグを行なうプラグインです。","parameters":{"Command Name":"Gamepad Config","Button Name":"Button %1","OK Button":"OK / Talk","OK Help":"Menu decision/This button is used when talking to people.","Cancel Button":"Cancel","Cancel Help":"This button is used to cancel menu actions.","Shift Button":"Dash","Shift Help":"When you press and hold, you can dash on the field.","Menu Button":"Menu","Menu Help":"Access the main menu from the field.","PageUp Button":"Page Up","PageUp Help":"You can quickly scroll up the menu.","PageDown Button":"Page Down","PageDown Help":"You can quickly scroll down the menu.","Reset Default":"Reset to Default","Reset Help":"Reset controller configuration to default.","Finish Config":"Finish Configuration","Finish Help":"Would you like to complete the gamepad configuration?"}},
{"name":"Yami_8DIR","status":true,"description":"プレイヤーの8方向の移動が可能になります。","parameters":{}},
{"name":"ScrollForceCenter","status":true,"description":"強制中央スクロールプラグイン","parameters":{"adjustX":"3","adjustY":"0"}},
{"name":"GraphicalDesignMode","status":true,"description":"GUI画面デザインプラグイン\r\nパラメータを変更したら「プロジェクトの保存」（Ctrl+S）","parameters":{"デザインモード":"false","自動保存":"true","モバイル版作成":"false","モバイル偽装":"false","ウィンドウ透過":"true","グリッドサイズ":"48","パディング":"0","フォントサイズ":"0","行の高さ":"0","背景透明度":"0","アイコンサイズ調整":"false","背景表示可否固定":"false","右クリックで消去":"false","メッセージウィンドウを無視":"false"}},
{"name":"K_MessageWindowAdjust","status":true,"description":"メッセージウィンドウ幅の調整をおこないます。","parameters":{}},
{"name":"111_InputForm","status":true,"description":"ゲーム画面上にHTMLの入力フォームを表示します","parameters":{"OK Button Text":"Yes","Display Cancel Button":"1","Cancel Button Text":"Cancel","Judge Switch Interval":"100","Switch ID Selected OK":"0","Force OK Switch ID":"0","Force Cancel Switch ID":"0"}},
{"name":"MenuSubCommand","status":true,"description":"メニュー画面のサブコマンドプラグイン","parameters":{"サブコマンド":"","コマンド追加位置":"0","サブメニュー横幅":"0","選択アクターID変数":"0","ウィンドウスキン":"","オプション消去":"true","ゲーム終了消去":"false","横並びサブメニュー":"false","サブメニュー逐次消去":"true","サブメニューX座標":"0","サブメニューY座標":"0","サブメニュー揃え":""}},
{"name":"NearEventSensor","status":true,"description":"周辺イベント感知プラグイン","parameters":{"デフォルトフラッシュ":"true","デフォルトフキダシ":"0","空イベントは無効":"true","感知距離":"11","フラッシュカラー":"","フラッシュ時間":"60","フキダシ間隔":"15","フキダシ完了までウェイト":"true","向きを考慮":"false"}},
{"name":"UTA_CommonSave","status":true,"description":"共有のセーブデータを作成し、指定したスイッチ・変数の状態をセーブデータ間で共有します。","parameters":{"Target Switches":"106-108,118,134,149,155,164,189,231,241,252,264,266-268,278-284","Target Variables":"","Is Auto":"true","Auto on Gameover":"false","Show Trace":"false"}},
{"name":"MPP_MapLight","status":true,"description":"【ver.1.2】マップの明るさを設定できるようにします。","parameters":{"Light Colors":"[\"255,255,255\",\"192,128,64\"]","Light Level 1 Regions":"1,9,17,25,33,41,49,57","Light Level 2 Regions":"2,10,18,26,34,42,50,58","Light Level 3 Regions":"3,11,19,27,35,43,51,59","Light Level 4 Regions":"4,12,20,28,36,44,52,60","Light Level 5 Regions":"5,13,21,29,37,45,53,61","Light Level 6 Regions":"6,14,22,30,38,46,54,62","Light Level 7 Regions":"7,15,23,31,39,47,55,63","=== Command ===":"","Plugin Commands":"{\"SetCharLight\":\"SetCharLight\",\"ShowMapLight\":\"ShowMapLight\",\"MoveMapLight\":\"MoveMapLight\",\"EraseMapLight\":\"EraseMapLight\",\"SetMapDarkness\":\"SetMapDarkness\"}","Map Metadata":"{\"Darkness\":\"Darkness\",\"MapLight\":\"MapLight\"}","Event Comments":"{\"Light\":\"灯り\"}"}},
{"name":"LoadComSim","status":true,"description":"ver1.00 メニューコマンドにロードを追加します。","parameters":{"loadtext":"Load"}},
{"name":"BalloonSkip","status":true,"description":"フキダシアイコン表示中、okキー/ctrlキー押下でそれを終了","parameters":{}}
];
